-- Tic Tac Tooth — complete database bootstrap
-- Generated by scripts/build-sql-bundle.mjs on 2026-08-25T06:19:15.494Z
--
-- 8 migrations plus the configuration seed, in order.
-- Run this once against an EMPTY database. It is not incremental and
-- re-running it on a database that already has data is not safe.
--
-- Contains no patient data and must never be given any.


-- ==========================================================================
-- 0001_schema.sql
-- ==========================================================================

-- =============================================================================
-- Tic Tac Tooth — core schema
--
-- Design notes that are load-bearing, recorded here because they are not
-- obvious from the DDL alone:
--
--  * Capacity is scoped by `resource_id`, not baked into the table. The clinic
--    runs one chair today; a second chair must be an INSERT, not a migration.
--
--  * Overlap is prevented by an exclusion constraint rather than by an
--    application-level "is this slot free?" check. The realistic failure is a
--    parent booking online at the same instant a receptionist creates an
--    appointment in that slot — no read-then-write check can close that race.
--
--  * `patients.date_of_birth`, never an age column. Age is a fact that goes
--    stale; a stored "7" is wrong within a year. `appointments.age_at_booking`
--    separately records what the parent stated at the time, which is immutable
--    and is a different thing.
--
--  * Timestamps are `timestamptz`. Opening hours are stored as local times and
--    resolved against a date in the clinic timezone. India observes no DST, so
--    that resolution is unambiguous — the same pattern would be a bug in most
--    other markets.
-- =============================================================================

create extension if not exists btree_gist;
create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------

create type app_role as enum ('admin', 'receptionist');

create type appointment_status as enum (
  'pending',    -- requested online, holding the slot, awaiting reception
  'confirmed',
  'cancelled',
  'completed',
  'no_show'
);

create type appointment_source as enum ('online', 'staff');

create type room_preference as enum ('space', 'jungle', 'no_preference');

-- ---------------------------------------------------------------------------
-- Staff
-- ---------------------------------------------------------------------------

create table profiles (
  id          uuid primary key references auth.users on delete cascade,
  role        app_role not null default 'receptionist',
  full_name   text not null,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

comment on table profiles is
  'Staff accounts. Created by an admin via the Admin API — there is no public sign-up.';

-- ---------------------------------------------------------------------------
-- Bookable capacity
-- ---------------------------------------------------------------------------

create table resources (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  is_active   boolean not null default true,
  sort_order  int not null default 0,
  created_at  timestamptz not null default now()
);

comment on table resources is
  'A bookable unit of capacity (a chair). One row today. Adding a second row '
  'raises clinic capacity to two concurrent appointments with no schema change.';

-- ---------------------------------------------------------------------------
-- Clinic configuration — exactly one row
-- ---------------------------------------------------------------------------

create table clinic_settings (
  id                     int primary key default 1,
  timezone               text not null default 'Asia/Kolkata',

  -- Granularity of the booking grid. NOT the length of an appointment —
  -- that comes from treatment_types.duration_minutes. Availability finds
  -- contiguous free time of at least the treatment's duration.
  slot_minutes           int  not null default 15,
  buffer_minutes         int  not null default 0,

  -- Opening hours, keyed by ISO weekday (1 = Monday .. 7 = Sunday):
  --   { "1": [{"opens":"10:00","closes":"13:00"},
  --           {"opens":"14:00","closes":"19:00"}], ... }
  -- An absent or empty weekday means closed.
  opening_hours          jsonb not null default '{}'::jsonb,

  booking_lead_hours     int  not null default 12,
  booking_horizon_days   int  not null default 60,

  -- How long an unconfirmed online request holds its slot before expiring.
  -- Without this, an abandoned request blocks that slot indefinitely.
  pending_ttl_hours      int  not null default 24,

  -- Ceilings for the public booking endpoint. Pending requests hold slots,
  -- so an unthrottled endpoint is a denial-of-service on the schedule.
  max_pending_per_mobile int  not null default 2,
  max_requests_per_ip_hr int  not null default 6,

  retention_months       int  not null default 84,

  -- Contact details, surfaced on the public site. These replace the
  -- [PLACEHOLDER] values previously hardcoded in lib/content/site.ts.
  phone_display          text,
  phone_href             text,
  whatsapp_href          text,
  timings_display        text,

  updated_at             timestamptz not null default now(),
  constraint clinic_settings_singleton check (id = 1)
);

comment on constraint clinic_settings_singleton on clinic_settings is
  'Enforces a single settings row. Without it a second row eventually appears '
  'and the application silently reads whichever it happens to find first.';

create table closures (
  id          uuid primary key default gen_random_uuid(),
  starts_on   date not null,
  ends_on     date not null,
  reason      text not null,
  created_at  timestamptz not null default now(),
  constraint closures_range_valid check (ends_on >= starts_on)
);

create table treatment_types (
  id               uuid primary key default gen_random_uuid(),
  name             text not null,
  slug             text not null unique,
  duration_minutes int  not null default 30,
  -- Emergencies, sedation and special-needs appointments always want a human
  -- to look before the slot is committed.
  requires_review  boolean not null default false,
  is_active        boolean not null default true,
  sort_order       int not null default 0,
  created_at       timestamptz not null default now(),
  constraint treatment_duration_positive check (duration_minutes > 0)
);

-- ---------------------------------------------------------------------------
-- Consent — stored as evidence, not as a boolean
-- ---------------------------------------------------------------------------

create table consent_texts (
  id          uuid primary key default gen_random_uuid(),
  version     int not null unique,
  body        text not null,
  effective_from timestamptz not null default now(),
  created_at  timestamptz not null default now()
);

comment on table consent_texts is
  'The verbatim wording of each consent version. Recording that a parent '
  'agreed to "version 3" is worthless in two years without version 3 itself.';

-- ---------------------------------------------------------------------------
-- Families and patients
-- ---------------------------------------------------------------------------

create table families (
  id             uuid primary key default gen_random_uuid(),
  contact_name   text not null,
  mobile         text not null,
  email          text,
  relationship   text not null,

  -- True for anything created by an anonymous online booking. Online bookings
  -- NEVER attach to an existing family: a mobile number typed into a public
  -- form is an unverified claim, and treating it as identity would hand one
  -- family's children and visit history to anyone who guessed the number.
  -- Reception merges duplicates deliberately, seeing both records.
  is_provisional boolean not null default false,

  notes          text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  -- Set when reception merges this record into another.
  merged_into_id uuid references families(id) on delete set null
);

create index families_mobile_idx on families (mobile);
create index families_merged_idx on families (merged_into_id)
  where merged_into_id is not null;

create table patients (
  id                  uuid primary key default gen_random_uuid(),
  family_id           uuid not null references families(id) on delete cascade,
  first_name          text not null,
  date_of_birth       date,
  accessibility_notes text,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create index patients_family_idx on patients (family_id);

-- ---------------------------------------------------------------------------
-- Appointments
-- ---------------------------------------------------------------------------

create table appointments (
  id                uuid primary key default gen_random_uuid(),
  reference         text not null unique,

  patient_id        uuid not null references patients(id) on delete cascade,
  resource_id       uuid not null references resources(id),
  treatment_type_id uuid references treatment_types(id),

  starts_at         timestamptz not null,
  ends_at           timestamptz not null,

  status            appointment_status not null default 'pending',
  source            appointment_source not null default 'online',
  room_preference   room_preference not null default 'no_preference',

  -- What the parent stated at booking time. Deliberately separate from
  -- patients.date_of_birth: this is a point-in-time claim, not a fact.
  age_at_booking    int,

  concern           text,
  staff_notes       text,

  -- Only meaningful while status = 'pending'.
  expires_at        timestamptz,

  created_by        uuid references profiles(id) on delete set null,
  confirmed_by      uuid references profiles(id) on delete set null,
  confirmed_at      timestamptz,
  cancelled_at      timestamptz,
  cancel_reason     text,

  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),

  constraint appointments_time_valid check (ends_at > starts_at),
  constraint appointments_age_sane
    check (age_at_booking is null or age_at_booking between 0 and 18)
);

-- The clinic treats patients aged 0-18. An 18-year-old booking for themselves
-- is an adult and sits outside the children's-data consent regime — flagged in
-- DECISIONS.md as a legal question, not silently handled here.

create index appointments_starts_idx on appointments (starts_at);
create index appointments_status_idx on appointments (status);
create index appointments_patient_idx on appointments (patient_id);
create index appointments_expiry_idx on appointments (expires_at)
  where status = 'pending';

-- The single most important constraint in this schema. Two writers racing for
-- the same slot cannot both win; the loser gets a constraint violation and
-- re-reads availability.
alter table appointments
  add constraint appointments_no_overlap
  exclude using gist (
    resource_id with =,
    tstzrange(starts_at, ends_at) with &&
  ) where (status in ('pending', 'confirmed'));

create table consents (
  id              uuid primary key default gen_random_uuid(),
  appointment_id  uuid not null references appointments(id) on delete cascade,
  family_id       uuid not null references families(id) on delete cascade,
  consent_text_id uuid not null references consent_texts(id),
  granted_by_name text not null,
  relationship    text not null,
  granted_at      timestamptz not null default now()
);

create index consents_appointment_idx on consents (appointment_id);

-- ---------------------------------------------------------------------------
-- Operational ledgers
-- ---------------------------------------------------------------------------

-- Rate-limiting ledger for the public booking endpoint.
create table booking_attempts (
  id          bigserial primary key,
  ip_hash     text,
  mobile      text,
  succeeded   boolean not null default false,
  created_at  timestamptz not null default now()
);

create index booking_attempts_ip_idx     on booking_attempts (ip_hash, created_at desc);
create index booking_attempts_mobile_idx on booking_attempts (mobile,  created_at desc);

create table notification_log (
  id             bigserial primary key,
  appointment_id uuid references appointments(id) on delete cascade,
  channel        text not null,
  template       text not null,
  status         text not null,
  provider_id    text,
  error          text,
  created_at     timestamptz not null default now()
);

create table audit_log (
  id          bigserial primary key,
  actor_id    uuid,
  action      text not null,
  entity      text not null,
  entity_id   uuid,
  diff        jsonb,
  created_at  timestamptz not null default now()
);

create index audit_log_entity_idx on audit_log (entity, entity_id, created_at desc);

comment on table audit_log is
  'Written by database triggers, never by application code. Audit rows emitted '
  'from server actions are lost silently the moment any path forgets to call '
  'the helper — not acceptable for access to children''s records.';


-- ==========================================================================
-- 0002_rls.sql
-- ==========================================================================

-- =============================================================================
-- Row Level Security — default deny, everywhere.
--
-- Supabase exposes these tables directly to the browser, and the anon key
-- ships inside the client bundle. If RLS is wrong here, a table of children's
-- names, dates of birth and parents' mobile numbers is world-readable by
-- anyone who opens devtools. There is no second line of defence.
--
-- The rules:
--   * `anon` gets NO table access at all. Not appointments, not patients,
--     not families, not even read-only.
--   * The public reaches the database through exactly two SECURITY DEFINER
--     functions (see 0003_functions.sql): one returns free times, one accepts
--     a booking request. Neither ever returns a patient row.
--   * Staff access is gated on a role read from `profiles`, and inactive
--     accounts are refused even if their session is still valid.
-- =============================================================================

alter table profiles          enable row level security;
alter table resources         enable row level security;
alter table clinic_settings   enable row level security;
alter table closures          enable row level security;
alter table treatment_types   enable row level security;
alter table consent_texts     enable row level security;
alter table families          enable row level security;
alter table patients          enable row level security;
alter table appointments      enable row level security;
alter table consents          enable row level security;
alter table booking_attempts  enable row level security;
alter table notification_log  enable row level security;
alter table audit_log         enable row level security;

-- No policies are declared for `anon` anywhere in this file. With RLS enabled
-- and no permissive policy, every anon read and write is refused by default.

-- ---------------------------------------------------------------------------
-- Role helpers
--
-- SECURITY DEFINER and a pinned search_path: without the pin, a caller who can
-- create objects in a schema earlier on the path could shadow `profiles` and
-- make this function return whatever they like.
-- ---------------------------------------------------------------------------

create or replace function auth_role()
returns app_role
language sql
stable
security definer
set search_path = public
as $$
  select role
  from profiles
  where id = auth.uid()
    and is_active            -- a deactivated account keeps its session but loses access
$$;

create or replace function is_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select auth_role() is not null
$$;

create or replace function is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select auth_role() = 'admin'
$$;

-- ---------------------------------------------------------------------------
-- profiles
-- ---------------------------------------------------------------------------

create policy profiles_self_read on profiles
  for select to authenticated
  using (id = auth.uid() or is_staff());

create policy profiles_admin_write on profiles
  for all to authenticated
  using (is_admin()) with check (is_admin());

-- ---------------------------------------------------------------------------
-- Reference data — staff read, admin write
-- ---------------------------------------------------------------------------

create policy resources_staff_read on resources
  for select to authenticated using (is_staff());
create policy resources_admin_write on resources
  for all to authenticated using (is_admin()) with check (is_admin());

create policy settings_staff_read on clinic_settings
  for select to authenticated using (is_staff());
create policy settings_admin_write on clinic_settings
  for all to authenticated using (is_admin()) with check (is_admin());

create policy closures_staff_read on closures
  for select to authenticated using (is_staff());
create policy closures_admin_write on closures
  for all to authenticated using (is_admin()) with check (is_admin());

create policy treatments_staff_read on treatment_types
  for select to authenticated using (is_staff());
create policy treatments_admin_write on treatment_types
  for all to authenticated using (is_admin()) with check (is_admin());

create policy consent_texts_staff_read on consent_texts
  for select to authenticated using (is_staff());
create policy consent_texts_admin_write on consent_texts
  for all to authenticated using (is_admin()) with check (is_admin());

-- ---------------------------------------------------------------------------
-- Patient data — staff only, no exceptions
-- ---------------------------------------------------------------------------

create policy families_staff_all on families
  for all to authenticated using (is_staff()) with check (is_staff());

create policy patients_staff_all on patients
  for all to authenticated using (is_staff()) with check (is_staff());

create policy appointments_staff_all on appointments
  for all to authenticated using (is_staff()) with check (is_staff());

create policy consents_staff_read on consents
  for select to authenticated using (is_staff());

-- Consent records are evidence. Staff may read them; nobody edits them
-- through the API, because an editable consent record proves nothing.
-- They are written only by the SECURITY DEFINER booking function.

-- ---------------------------------------------------------------------------
-- Ledgers
-- ---------------------------------------------------------------------------

create policy notifications_staff_read on notification_log
  for select to authenticated using (is_staff());

create policy audit_admin_read on audit_log
  for select to authenticated using (is_admin());

-- booking_attempts has no policy at all: it is written only by the booking
-- function running as definer, and read by nobody through the API.

-- ---------------------------------------------------------------------------
-- Realtime
--
-- Realtime honours RLS, so only staff sessions receive appointment payloads.
-- Worth being explicit that these payloads carry children's data — this
-- publication must never be widened to anon.
-- ---------------------------------------------------------------------------

alter publication supabase_realtime add table appointments;


-- ==========================================================================
-- 0003_functions.sql
-- ==========================================================================

-- =============================================================================
-- The only two entry points the anonymous public gets.
--
-- Both are SECURITY DEFINER, so they bypass RLS deliberately and must police
-- themselves. Neither ever returns a patient, family or appointment row.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Expire stale pending requests.
--
-- A pending request holds its slot. Without expiry, a parent who abandons the
-- form halfway blocks that slot forever. Called by the availability function
-- (so availability is always truthful) and by a scheduled job.
-- ---------------------------------------------------------------------------

create or replace function expire_stale_pending()
returns int
language plpgsql
security definer
set search_path = public
as $$
declare
  n int;
begin
  with expired as (
    update appointments
       set status        = 'cancelled',
           cancelled_at  = now(),
           cancel_reason = 'Expired — not confirmed in time'
     where status = 'pending'
       and expires_at is not null
       and expires_at < now()
    returning 1
  )
  select count(*) into n from expired;
  return n;
end;
$$;

-- ---------------------------------------------------------------------------
-- Free slots for a given date.
--
-- Returns times only. It deliberately does NOT return appointment rows: a
-- naive `select starts_at from appointments` to build the public booking
-- calendar would let anyone enumerate exactly when identifiable children are
-- in the building.
--
-- We do accept that a missing slot implies *someone* is booked. That is
-- unavoidable in any booking system and is acceptable — it reveals that the
-- clinic is busy, never who is in the chair.
-- ---------------------------------------------------------------------------

create or replace function get_available_slots(
  p_date date,
  p_treatment_type_id uuid default null
)
returns table (slot_start timestamptz)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  s              clinic_settings%rowtype;
  v_duration     int;
  v_tz           text;
  v_weekday      text;
  v_window       jsonb;
  v_open         timestamptz;
  v_close        timestamptz;
  v_cursor       timestamptz;
  v_earliest     timestamptz;
  v_latest       date;
begin
  select * into s from clinic_settings where id = 1;
  if not found then
    return;
  end if;

  v_tz := s.timezone;

  -- Closed all day?
  if exists (select 1 from closures c
              where p_date between c.starts_on and c.ends_on) then
    return;
  end if;

  -- Outside the bookable window?
  v_earliest := now() + make_interval(hours => s.booking_lead_hours);
  v_latest   := (now() at time zone v_tz)::date
                + make_interval(days => s.booking_horizon_days);
  if p_date > v_latest then
    return;
  end if;

  select coalesce(
           (select duration_minutes from treatment_types
             where id = p_treatment_type_id and is_active),
           30)
    into v_duration;

  v_weekday := extract(isodow from p_date)::text;

  for v_window in
    select * from jsonb_array_elements(coalesce(s.opening_hours -> v_weekday, '[]'::jsonb))
  loop
    v_open  := (p_date || ' ' || (v_window ->> 'opens')  )::timestamp at time zone v_tz;
    v_close := (p_date || ' ' || (v_window ->> 'closes') )::timestamp at time zone v_tz;

    v_cursor := v_open;
    while v_cursor + make_interval(mins => v_duration) <= v_close loop
      if v_cursor >= v_earliest
         and not exists (
           select 1
             from appointments a
            where a.status in ('pending', 'confirmed')
              and tstzrange(a.starts_at, a.ends_at)
                  && tstzrange(v_cursor,
                               v_cursor + make_interval(mins => v_duration + s.buffer_minutes))
         )
      then
        slot_start := v_cursor;
        return next;
      end if;

      v_cursor := v_cursor + make_interval(mins => s.slot_minutes);
    end loop;
  end loop;
end;
$$;

-- ---------------------------------------------------------------------------
-- Accept a booking request from the public site.
--
-- Writes family + patient + appointment + consent atomically, and returns only
-- a reference code.
--
-- Two things this deliberately does NOT do:
--
--  1. It never attaches to an existing family, even when the mobile number
--     matches one. A mobile typed into a public form is an unverified claim;
--     honouring it would hand one family's children and visit history to
--     anyone who guessed the number. Every online booking creates a
--     provisional family, and reception merges duplicates by hand.
--
--  2. It never trusts the caller for timing. Duration comes from the treatment
--     type, and the slot is re-validated here — a client could otherwise post
--     any start time it liked, including outside opening hours.
-- ---------------------------------------------------------------------------

create or replace function request_appointment(
  p_starts_at         timestamptz,
  p_treatment_type_id uuid,
  p_room_preference   room_preference,
  p_concern           text,
  p_patient_first_name text,
  p_patient_dob       date,
  p_accessibility_notes text,
  p_parent_name       text,
  p_parent_mobile     text,
  p_parent_email      text,
  p_relationship      text,
  p_ip_hash           text
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  s               clinic_settings%rowtype;
  v_duration      int;
  v_resource      uuid;
  v_family        uuid;
  v_patient       uuid;
  v_appointment   uuid;
  v_consent_text  uuid;
  v_reference     text;
  v_age           int;
begin
  select * into s from clinic_settings where id = 1;
  if not found then
    raise exception 'Clinic settings are not configured' using errcode = 'P0002';
  end if;

  -- Free anything that has timed out, so the availability check below is honest.
  perform expire_stale_pending();

  -- --- rate limiting ------------------------------------------------------
  -- Pending requests hold slots, so an unthrottled endpoint is a denial of
  -- service on the clinic's entire schedule, not merely spam.
  if p_ip_hash is not null and (
       select count(*) from booking_attempts
        where ip_hash = p_ip_hash
          and created_at > now() - interval '1 hour'
     ) >= s.max_requests_per_ip_hr then
    insert into booking_attempts (ip_hash, mobile, succeeded)
      values (p_ip_hash, p_parent_mobile, false);
    raise exception 'Too many booking attempts. Please call the clinic.'
      using errcode = 'P0001';
  end if;

  if (
       select count(*) from appointments a
         join patients pt on pt.id = a.patient_id
         join families f  on f.id  = pt.family_id
        where f.mobile = p_parent_mobile
          and a.status = 'pending'
     ) >= s.max_pending_per_mobile then
    insert into booking_attempts (ip_hash, mobile, succeeded)
      values (p_ip_hash, p_parent_mobile, false);
    raise exception 'You already have a pending request. Please call the clinic.'
      using errcode = 'P0001';
  end if;

  -- --- validate the slot server-side --------------------------------------
  select duration_minutes into v_duration
    from treatment_types
   where id = p_treatment_type_id and is_active;
  if v_duration is null then
    raise exception 'Unknown treatment type' using errcode = 'P0002';
  end if;

  if not exists (
    select 1
      from get_available_slots((p_starts_at at time zone s.timezone)::date,
                               p_treatment_type_id) g
     where g.slot_start = p_starts_at
  ) then
    raise exception 'That time is no longer available' using errcode = 'P0001';
  end if;

  select id into v_resource
    from resources where is_active order by sort_order limit 1;
  if v_resource is null then
    raise exception 'No bookable resource configured' using errcode = 'P0002';
  end if;

  select id into v_consent_text
    from consent_texts order by version desc limit 1;
  if v_consent_text is null then
    raise exception 'No consent text configured' using errcode = 'P0002';
  end if;

  -- --- write --------------------------------------------------------------
  insert into families (contact_name, mobile, email, relationship, is_provisional)
    values (p_parent_name, p_parent_mobile, p_parent_email, p_relationship, true)
    returning id into v_family;

  insert into patients (family_id, first_name, date_of_birth, accessibility_notes)
    values (v_family, p_patient_first_name, p_patient_dob, p_accessibility_notes)
    returning id into v_patient;

  v_age := case
             when p_patient_dob is null then null
             else extract(year from age(p_patient_dob))::int
           end;

  v_reference := upper(substr(encode(gen_random_bytes(4), 'hex'), 1, 6));

  -- The exclusion constraint may still reject this insert if a receptionist
  -- took the slot between the availability check above and this write. That is
  -- the race the constraint exists for; the caller re-reads availability.
  insert into appointments (
    reference, patient_id, resource_id, treatment_type_id,
    starts_at, ends_at, status, source, room_preference,
    age_at_booking, concern, expires_at
  ) values (
    v_reference, v_patient, v_resource, p_treatment_type_id,
    p_starts_at, p_starts_at + make_interval(mins => v_duration),
    'pending', 'online', coalesce(p_room_preference, 'no_preference'),
    v_age, p_concern,
    now() + make_interval(hours => s.pending_ttl_hours)
  ) returning id into v_appointment;

  insert into consents (
    appointment_id, family_id, consent_text_id, granted_by_name, relationship
  ) values (
    v_appointment, v_family, v_consent_text, p_parent_name, p_relationship
  );

  insert into booking_attempts (ip_hash, mobile, succeeded)
    values (p_ip_hash, p_parent_mobile, true);

  return v_reference;
end;
$$;

-- Grant execute narrowly. These two functions are the entire public surface.
revoke all on function get_available_slots(date, uuid) from public;
revoke all on function request_appointment(
  timestamptz, uuid, room_preference, text, text, date, text,
  text, text, text, text, text) from public;

grant execute on function get_available_slots(date, uuid) to anon, authenticated;
grant execute on function request_appointment(
  timestamptz, uuid, room_preference, text, text, date, text,
  text, text, text, text, text) to anon, authenticated;

-- expire_stale_pending is called internally and by the scheduled job only.
revoke all on function expire_stale_pending() from public;
grant execute on function expire_stale_pending() to authenticated, service_role;


-- ==========================================================================
-- 0004_audit.sql
-- ==========================================================================

-- =============================================================================
-- Audit logging, by trigger.
--
-- Deliberately not done in application code. An audit row emitted from a
-- server action disappears the moment any code path forgets to call the
-- helper, and nothing fails loudly when it does. For access to children's
-- records that is not good enough — the log has to be impossible to bypass,
-- including by a future developer who adds a new write path.
-- =============================================================================

create or replace function audit_row_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_diff jsonb;
  v_id   uuid;
begin
  if tg_op = 'DELETE' then
    v_diff := to_jsonb(old);
    v_id   := old.id;
  elsif tg_op = 'INSERT' then
    v_diff := to_jsonb(new);
    v_id   := new.id;
  else
    -- Only the fields that actually changed, so the log stays readable.
    select jsonb_object_agg(key, jsonb_build_object('from', old_v, 'to', new_v))
      into v_diff
      from (
        select n.key, o.value as old_v, n.value as new_v
          from jsonb_each(to_jsonb(new)) n
          join jsonb_each(to_jsonb(old)) o using (key)
         where n.value is distinct from o.value
      ) changed;
    v_id := new.id;
  end if;

  insert into audit_log (actor_id, action, entity, entity_id, diff)
    values (auth.uid(), tg_op, tg_table_name, v_id, v_diff);

  return coalesce(new, old);
end;
$$;

create trigger audit_appointments
  after insert or update or delete on appointments
  for each row execute function audit_row_change();

create trigger audit_patients
  after insert or update or delete on patients
  for each row execute function audit_row_change();

create trigger audit_families
  after insert or update or delete on families
  for each row execute function audit_row_change();

create trigger audit_profiles
  after insert or update or delete on profiles
  for each row execute function audit_row_change();

create trigger audit_settings
  after update on clinic_settings
  for each row execute function audit_row_change();

-- ---------------------------------------------------------------------------
-- updated_at maintenance
-- ---------------------------------------------------------------------------

create or replace function touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger touch_appointments before update on appointments
  for each row execute function touch_updated_at();
create trigger touch_patients before update on patients
  for each row execute function touch_updated_at();
create trigger touch_families before update on families
  for each row execute function touch_updated_at();
create trigger touch_profiles before update on profiles
  for each row execute function touch_updated_at();
create trigger touch_settings before update on clinic_settings
  for each row execute function touch_updated_at();

-- ---------------------------------------------------------------------------
-- Erasure on request (DPDP)
--
-- Hard delete, not a soft flag — an erasure request that leaves the data in
-- place has not been honoured. The deletion event itself is recorded, which is
-- the one trace that must survive.
-- ---------------------------------------------------------------------------

create or replace function erase_family(p_family_id uuid, p_reason text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_patients int;
  v_appts    int;
begin
  if not is_admin() then
    raise exception 'Only an administrator may erase records'
      using errcode = '42501';
  end if;

  select count(*) into v_patients from patients where family_id = p_family_id;
  select count(*) into v_appts
    from appointments a join patients p on p.id = a.patient_id
   where p.family_id = p_family_id;

  -- Recorded before the cascade removes the rows that the triggers would
  -- otherwise log individually.
  insert into audit_log (actor_id, action, entity, entity_id, diff)
    values (auth.uid(), 'ERASE', 'families', p_family_id,
            jsonb_build_object('reason',   p_reason,
                               'patients', v_patients,
                               'appointments', v_appts));

  delete from families where id = p_family_id;
end;
$$;

revoke all on function erase_family(uuid, text) from public;
grant execute on function erase_family(uuid, text) to authenticated;

-- ---------------------------------------------------------------------------
-- Retention purge, run on a schedule
-- ---------------------------------------------------------------------------

create or replace function purge_expired_records()
returns int
language plpgsql
security definer
set search_path = public
as $$
declare
  s clinic_settings%rowtype;
  n int;
begin
  select * into s from clinic_settings where id = 1;
  if not found then return 0; end if;

  with gone as (
    delete from families f
     where not exists (
       select 1 from patients p
         join appointments a on a.patient_id = p.id
        where p.family_id = f.id
          and a.starts_at > now() - make_interval(months => s.retention_months)
     )
     and f.created_at < now() - make_interval(months => s.retention_months)
    returning 1
  )
  select count(*) into n from gone;

  insert into audit_log (actor_id, action, entity, entity_id, diff)
    values (null, 'PURGE', 'families', null,
            jsonb_build_object('removed', n,
                               'retention_months', s.retention_months));
  return n;
end;
$$;

revoke all on function purge_expired_records() from public;
grant execute on function purge_expired_records() to service_role;


-- ==========================================================================
-- 0005_public_config.sql
-- ==========================================================================

-- Public configuration read path.
--
-- The booking form needs the list of treatment types, and the marketing pages
-- need the clinic's phone number and timings. Both are non-sensitive, but the
-- security model rests on one absolute: `anon` has NO table access. A policy
-- granting anon SELECT on treatment_types would be harmless in itself and
-- would also make that sentence untrue — after which every later reviewer has
-- to check which tables are the exceptions.
--
-- So config is read the same way bookings are written: through a narrow
-- SECURITY DEFINER function with an explicit column list. The column list is
-- the point. `select *` here would mean that adding, say, an internal note
-- field to clinic_settings later silently publishes it to the internet.

-- Active treatments, in display order. Duration is included because the
-- booking form shows "about 45 minutes" before a parent commits to a slot.
create or replace function get_treatment_types()
returns table (
  id               uuid,
  name             text,
  slug             text,
  duration_minutes int
)
language sql
stable
security definer
set search_path = public
as $$
  select t.id, t.name, t.slug, t.duration_minutes
    from treatment_types t
   where t.is_active
   order by t.sort_order, t.name;
$$;

-- Contact details and opening hours only. Explicitly NOT the rate-limit
-- ceilings, the pending TTL or the retention period — publishing the limits
-- of the throttle to the people it throttles is free reconnaissance.
create or replace function get_public_config()
returns table (
  phone_display        text,
  phone_href           text,
  whatsapp_href        text,
  timings_display      text,
  opening_hours        jsonb,
  timezone             text,
  booking_horizon_days int,
  booking_lead_hours   int
)
language sql
stable
security definer
set search_path = public
as $$
  select s.phone_display, s.phone_href, s.whatsapp_href, s.timings_display,
         s.opening_hours, s.timezone, s.booking_horizon_days, s.booking_lead_hours
    from clinic_settings s
   where s.id = 1;
$$;

revoke all on function get_treatment_types() from public;
revoke all on function get_public_config()   from public;
grant execute on function get_treatment_types() to anon, authenticated;
grant execute on function get_public_config()   to anon, authenticated;


-- ==========================================================================
-- 0006_merge.sql
-- ==========================================================================

-- Family merge.
--
-- This is the other half of the decision that online bookings never attach to
-- an existing family. That rule is what stops an anonymous visitor inheriting
-- someone else's children by typing their mobile number — but it guarantees
-- duplicates whenever a returning parent books online. Merging is how those
-- duplicates get reconciled, and it is a *staff* action performed while
-- looking at both records, not an inference drawn from a form field.
--
-- The source family is not deleted. `merged_into_id` leaves a trail, so a
-- mistaken merge can be understood afterwards; erase_family remains the only
-- thing that actually removes a family, and it is admin-only.

create or replace function merge_families(
  p_source_id uuid,
  p_target_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_moved int;
begin
  if not is_staff() then
    raise exception 'Only staff may merge records' using errcode = '42501';
  end if;

  if p_source_id = p_target_id then
    raise exception 'A family cannot be merged into itself';
  end if;

  -- Merging into an already-merged record would build a chain that reception
  -- has no way to see. Make them pick the surviving record.
  if exists (select 1 from families
              where id = p_target_id and merged_into_id is not null) then
    raise exception 'That record has itself been merged. Choose the current record instead.';
  end if;

  if exists (select 1 from families
              where id = p_source_id and merged_into_id is not null) then
    raise exception 'That record has already been merged.';
  end if;

  if not exists (select 1 from families where id = p_target_id) then
    raise exception 'The record being merged into no longer exists.';
  end if;

  -- Children move to the surviving family. Appointments follow their patient,
  -- so visit history travels with them and nothing needs rewriting.
  update patients set family_id = p_target_id, updated_at = now()
   where family_id = p_source_id;
  get diagnostics v_moved = row_count;

  -- Consents record who granted permission and stay attached to the family
  -- that granted them: re-pointing them would misrepresent the evidence.

  update families
     set merged_into_id = p_target_id,
         updated_at     = now()
   where id = p_source_id;

  -- The surviving record is now the confirmed one — a merge is a member of
  -- staff vouching for the identity that an online form could not.
  update families
     set is_provisional = false,
         updated_at     = now()
   where id = p_target_id;

  insert into audit_log (actor_id, action, entity, entity_id, diff)
    values (auth.uid(), 'MERGE', 'families', p_source_id,
            jsonb_build_object('into', p_target_id, 'patients_moved', v_moved));
end;
$$;

revoke all on function merge_families(uuid, uuid) from public;
grant execute on function merge_families(uuid, uuid) to authenticated;


-- ==========================================================================
-- 0007_audit_redaction.sql
-- ==========================================================================

-- =============================================================================
-- Two defects in the audit design, both of which defeat erasure.
--
-- DEFECT 1 — the audit log was a shadow copy of every patient record.
--
--   audit_row_change() wrote to_jsonb(new) on INSERT and to_jsonb(old) on
--   DELETE. So every family insert copied the parent's name, mobile and email
--   into audit_log, every patient insert copied a child's first name and date
--   of birth, and every delete copied the whole row again on the way out.
--
--   The consequence is that erase_family did not erase. It deleted the
--   families row, the cascade deleted the children, and every one of those
--   deletions wrote the full record into a table that erase_family does not
--   touch — with audit_log readable by any administrator. A parent exercising
--   their right to erasure under DPDP Act 2023 §9 would have had their child's
--   name and date of birth moved, not removed. The same applies to the
--   retention purge: data past its retention period survived in the log.
--
--   Fix: for tables holding patient data, the log records WHICH COLUMNS
--   changed, never their values. That still answers the questions an audit log
--   exists to answer — who touched this record, when, and what kind of change
--   was it — and it stops the log accumulating the data it is auditing.
--
--   Config tables keep full values, because "who changed the opening hours
--   from what to what" is the whole point there and none of it is personal.
--
-- DEFECT 2 — staff could delete patient records directly.
--
--   families_staff_all granted `for all`, which includes DELETE. A
--   receptionist could therefore delete a family through the ordinary API,
--   bypassing erase_family entirely — bypassing its admin-only check and the
--   recorded reason that makes an erasure demonstrable afterwards.
--
--   Fix: no policy grants DELETE on families or patients. erase_family is
--   SECURITY DEFINER, so it still works; it becomes the only way.
-- =============================================================================

-- Tables whose column VALUES must never enter the audit log.
create or replace function audit_is_personal(p_table text)
returns boolean
language sql
immutable
as $$
  select p_table in ('families', 'patients', 'appointments', 'consents');
$$;

create or replace function audit_row_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_diff     jsonb;
  v_id       uuid;
  v_personal boolean := audit_is_personal(tg_table_name);
begin
  if tg_op = 'DELETE' then
    v_id   := old.id;
    v_diff := case when v_personal
                   then jsonb_build_object('redacted', true)
                   else to_jsonb(old) end;

  elsif tg_op = 'INSERT' then
    v_id   := new.id;
    v_diff := case when v_personal
                   then jsonb_build_object('redacted', true)
                   else to_jsonb(new) end;

  else
    v_id := new.id;

    if v_personal then
      -- Column names only. Enough to see that a child's date of birth was
      -- edited, without the log holding either the old or the new one.
      select jsonb_build_object(
               'redacted', true,
               'fields', coalesce(jsonb_agg(key order by key), '[]'::jsonb))
        into v_diff
        from (
          select n.key
            from jsonb_each(to_jsonb(new)) n
            join jsonb_each(to_jsonb(old)) o using (key)
           where n.value is distinct from o.value
        ) changed;
    else
      select jsonb_object_agg(key, jsonb_build_object('from', old_v, 'to', new_v))
        into v_diff
        from (
          select n.key, o.value as old_v, n.value as new_v
            from jsonb_each(to_jsonb(new)) n
            join jsonb_each(to_jsonb(old)) o using (key)
           where n.value is distinct from o.value
        ) changed;
    end if;
  end if;

  insert into audit_log (actor_id, action, entity, entity_id, diff)
    values (auth.uid(), tg_op, tg_table_name, v_id, v_diff);

  return coalesce(new, old);
end;
$$;

-- Any rows written by the previous version already hold patient data. Redact
-- them rather than leaving the defect behind in historical rows.
update audit_log
   set diff = jsonb_build_object('redacted', true, 'redacted_by', 'migration 0007')
 where audit_is_personal(entity)
   and diff is not null
   and not (diff ? 'redacted');

-- ---------------------------------------------------------------------------
-- Close the direct-delete path
-- ---------------------------------------------------------------------------

drop policy if exists families_staff_all on families;
drop policy if exists patients_staff_all on patients;

create policy families_staff_read on families
  for select to authenticated using (is_staff());
create policy families_staff_insert on families
  for insert to authenticated with check (is_staff());
create policy families_staff_update on families
  for update to authenticated using (is_staff()) with check (is_staff());

create policy patients_staff_read on patients
  for select to authenticated using (is_staff());
create policy patients_staff_insert on patients
  for insert to authenticated with check (is_staff());
create policy patients_staff_update on patients
  for update to authenticated using (is_staff()) with check (is_staff());

-- Deliberately no DELETE policy on either table. Removing a child's record is
-- erase_family's job: admin-only, reason required, and logged as an erasure.

-- Appointments keep their delete path closed for the same reason — a
-- cancelled appointment is a status, not an absence. Cancelling preserves the
-- history reception needs; deleting hides that anything ever happened.
drop policy if exists appointments_staff_all on appointments;

create policy appointments_staff_read on appointments
  for select to authenticated using (is_staff());
create policy appointments_staff_insert on appointments
  for insert to authenticated with check (is_staff());
create policy appointments_staff_update on appointments
  for update to authenticated using (is_staff()) with check (is_staff());


-- ==========================================================================
-- 0008_ledger_retention.sql
-- ==========================================================================

-- =============================================================================
-- Retention for the two ledgers, which the original purge missed.
--
-- `purge_expired_records` removed families past the retention period and
-- nothing else. Two tables were quietly accumulating personal data outside
-- that period, and outside what the privacy notice tells parents:
--
--  1. booking_attempts stores the parent's mobile number in the clear, so that
--     the rate limiter can count pending requests per mobile. That is a fair
--     use, but the count only looks back an hour or so — the row is useless
--     within a day and was being kept forever. A mobile number is personal
--     data whether or not we think of the table as a ledger, and it survived
--     erase_family entirely: a parent could ask for erasure, be told it was
--     done, and leave their number behind in a table nobody thought about.
--
--  2. notification_log.error stores whatever the email or WhatsApp provider
--     said went wrong, which routinely includes the recipient's address.
--     The row cascades when the appointment goes, so the retention purge and
--     erasure both reach it — but a failed send for an appointment that was
--     never created leaves the address with nothing to cascade from.
--
-- Fix: both are trimmed on the same schedule as everything else, and
-- erase_family now clears the attempts belonging to the family it erases.
-- =============================================================================

-- Long enough to investigate a burst of abuse, far beyond any rate-limit
-- window, and short enough that a mobile number is not sitting there a month
-- later for no reason.
create or replace function purge_ledgers()
returns int
language plpgsql
security definer
set search_path = public
as $$
declare
  n_attempts int;
  n_notifs   int;
begin
  with gone as (
    delete from booking_attempts
     where created_at < now() - interval '7 days'
    returning 1
  )
  select count(*) into n_attempts from gone;

  -- Orphans only: anything still attached to an appointment is governed by
  -- that appointment's retention and must not be trimmed out from under it.
  with gone as (
    delete from notification_log
     where appointment_id is null
       and created_at < now() - interval '30 days'
    returning 1
  )
  select count(*) into n_notifs from gone;

  insert into audit_log (actor_id, action, entity, entity_id, diff)
    values (null, 'PURGE', 'ledgers', null,
            jsonb_build_object('booking_attempts', n_attempts,
                               'notification_log', n_notifs));

  return n_attempts + n_notifs;
end;
$$;

revoke all on function purge_ledgers() from public;
grant execute on function purge_ledgers() to service_role;

-- ---------------------------------------------------------------------------
-- Erasure must reach the rate-limit ledger too
-- ---------------------------------------------------------------------------

create or replace function erase_family(p_family_id uuid, p_reason text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_patients int;
  v_appts    int;
  v_mobile   text;
begin
  if not is_admin() then
    raise exception 'Only an administrator may erase records'
      using errcode = '42501';
  end if;

  select mobile into v_mobile from families where id = p_family_id;

  select count(*) into v_patients from patients where family_id = p_family_id;
  select count(*) into v_appts
    from appointments a join patients p on p.id = a.patient_id
   where p.family_id = p_family_id;

  -- Recorded before the cascade removes the rows that the triggers would
  -- otherwise log individually.
  --
  -- The reason is free text typed by a member of staff. It is stored because
  -- "deleted on this date, because they asked" is what makes the erasure
  -- demonstrable — but it is the one field here that could contain a name if
  -- someone types one, which is why the admin UI asks them not to and the
  -- privacy notice says plainly that a reason is kept.
  insert into audit_log (actor_id, action, entity, entity_id, diff)
    values (auth.uid(), 'ERASE', 'families', p_family_id,
            jsonb_build_object('reason',   p_reason,
                               'patients', v_patients,
                               'appointments', v_appts));

  delete from families where id = p_family_id;

  -- Not covered by the cascade: booking_attempts has no foreign key, by
  -- design, because it must accept rows for bookings that were rejected and
  -- therefore never became a family.
  if v_mobile is not null then
    delete from booking_attempts where mobile = v_mobile;
  end if;
end;
$$;

revoke all on function erase_family(uuid, text) from public;
grant execute on function erase_family(uuid, text) to authenticated;


-- ==========================================================================
-- seed.sql — configuration only
-- ==========================================================================

-- =============================================================================
-- Seed data.
--
-- Contains no patient data of any kind — only configuration. Fixtures for
-- testing are created by the test scripts so they can be torn down cleanly.
-- =============================================================================

insert into resources (name, sort_order) values ('Main chair', 0);

insert into clinic_settings (
  id, timezone, slot_minutes, buffer_minutes,
  opening_hours,
  booking_lead_hours, booking_horizon_days, pending_ttl_hours,
  max_pending_per_mobile, max_requests_per_ip_hr, retention_months,
  phone_display, phone_href, whatsapp_href, timings_display
) values (
  1, 'Asia/Kolkata', 15, 0,
  -- ISO weekday keys, 1 = Monday. Sunday (7) absent means closed.
  -- Split windows model the lunch break. [PLACEHOLDER: confirm real hours.]
  '{
    "1": [{"opens":"10:00","closes":"13:00"},{"opens":"14:00","closes":"19:00"}],
    "2": [{"opens":"10:00","closes":"13:00"},{"opens":"14:00","closes":"19:00"}],
    "3": [{"opens":"10:00","closes":"13:00"},{"opens":"14:00","closes":"19:00"}],
    "4": [{"opens":"10:00","closes":"13:00"},{"opens":"14:00","closes":"19:00"}],
    "5": [{"opens":"10:00","closes":"13:00"},{"opens":"14:00","closes":"19:00"}],
    "6": [{"opens":"10:00","closes":"13:00"},{"opens":"14:00","closes":"19:00"}]
  }'::jsonb,
  12, 60, 24,
  2, 6, 84,
  '[PLACEHOLDER: +91 9XXXX XXXXX]',
  'tel:+919000000000',
  'https://wa.me/919000000000',
  '[PLACEHOLDER: Mon–Sat, 10:00 AM – 7:00 PM IST]'
);

-- Treatment types available for online booking. `requires_review` is advisory
-- for reception — every online booking is pending regardless.
insert into treatment_types (name, slug, duration_minutes, requires_review, sort_order) values
  ('Routine check-up',                        'routine-check-up',       30, false, 0),
  ('Tooth pain or sensitivity',               'tooth-pain',             30, true,  1),
  ('Chipped, cracked or knocked-out tooth',   'dental-trauma',          45, true,  2),
  ('Cavity or filling',                       'cavity-filling',         45, false, 3),
  ('Braces or clear aligners consultation',   'orthodontic-consult',    45, false, 4),
  ('Special-needs / sensory-adapted visit',   'special-needs',          60, true,  5),
  ('Something else',                          'other',                  30, true,  6);

-- Version 1 of the consent wording. Stored verbatim so that a consent record
-- pointing at "version 1" still means something years later.
--
-- [LEGAL REVIEW REQUIRED] This is placeholder wording. It must be replaced
-- with text reviewed against DPDP Act 2023 §9 before the site goes live and
-- begins storing real children's data.
insert into consent_texts (version, body) values (
  1,
  'I confirm I am this child''s parent or legal guardian, and I consent to '
  'their information being used solely to schedule and prepare for this '
  'dental appointment. I understand I can ask for these records to be '
  'deleted at any time. [PLACEHOLDER — pending legal review.]'
);
